checkpoint: "checkpoints/20231026-723.pt"
device: "cpu"
length_multiplier: 1.05

tokenizer:
  tokenizer_file: "files/tokenizer.json"
  vocab_path: "files/vocab.txt"

data:
  sampling_rate: 16000
  n_mel_channels: 40
  hop_length: 200
  n_ftt: 400
  training_file: "files/train.csv"
  testing_file: "files/test.csv"
  max_str_len: 250
  descending_order: False
  sep: "_"
  csv_file_keys:
    duration: "duration"
    path: "audio_path"
    text: "text"

training:
  checkpoints_dir: "checkpoints"
  batch_size: 8
  optimizer: "sgd"
  epochs: 7
  optim:
    learning_rate: 0.05
    momentum: 0.9

model:
  decoder:
    emb_dim: 512
    hidden_size: 256
    n_layers: 2
    dropout: 0.1
    rnn_type: "lstm"

  encoder:
    input_size: ${data.n_mel_channels}
    n_layers: 2
    dropout: 0.1
    is_bidirectional: true
    hidden_size: 128 # half pred_net hidden_size if bidirectional
    rnn_type: "lstm"

  joint:
    input_size: ${model.decoder.hidden_size}
